// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4w93Si9SnMSxPSZEZy36U-3z5W2GQ3TI',
    appId: '1:261024735177:web:c3aaa24b8f369e23189218',
    messagingSenderId: '261024735177',
    projectId: 'chess-acc5a',
    authDomain: 'chess-acc5a.firebaseapp.com',
    storageBucket: 'chess-acc5a.firebasestorage.app',
    measurementId: 'G-9P3H9SH2DK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPgpO--n6l3VsAOOfkErcTShRkBOHlcv8',
    appId: '1:261024735177:android:ea63055289f1c991189218',
    messagingSenderId: '261024735177',
    projectId: 'chess-acc5a',
    storageBucket: 'chess-acc5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtehbe-nDyB8N1kYix-xXeDjbmIXQFy9E',
    appId: '1:261024735177:ios:c3a88af5beef5b2c189218',
    messagingSenderId: '261024735177',
    projectId: 'chess-acc5a',
    storageBucket: 'chess-acc5a.firebasestorage.app',
    iosBundleId: 'com.foundercode.customChess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtehbe-nDyB8N1kYix-xXeDjbmIXQFy9E',
    appId: '1:261024735177:ios:c3a88af5beef5b2c189218',
    messagingSenderId: '261024735177',
    projectId: 'chess-acc5a',
    storageBucket: 'chess-acc5a.firebasestorage.app',
    iosBundleId: 'com.foundercode.customChess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4w93Si9SnMSxPSZEZy36U-3z5W2GQ3TI',
    appId: '1:261024735177:web:8aa8f84e77d50202189218',
    messagingSenderId: '261024735177',
    projectId: 'chess-acc5a',
    authDomain: 'chess-acc5a.firebaseapp.com',
    storageBucket: 'chess-acc5a.firebasestorage.app',
    measurementId: 'G-GCPCS8SJHB',
  );
}
